image: python:3.7-alpine

stages:
 - test
 - publish

test-all:

publish-docs: 
  stage: publish
  script:
  - pip install -U sphinx
  - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

