version: "3.3"
services:
  pytest:
    build: .
    command: pytest --verbose -s tests
    volumes:
      - '.:/app'
    networks:
      - arango-net
    depends_on:
      - arangodb
  arangodb:
    image: arangodb
    environment:
      ARANGO_NO_AUTH: 1
    networks:
      - arango-net
networks:
  arango-net:
