[annotator]

    [annotator.NamedEntityAnnotator] ## ner is the key for this annotator to get all the variables
    annotator_class ="cag.graph_framework.components.annotators.instance.ner_annotator.NamedEntityAnnotator"
    vertex_class = "cag.graph_framework.components.annotators.element.graph_elements.NamedEntityNode"
    edge_class = "cag.graph_framework.components.annotators.element.graph_elements.HasAnnotation"
    pipe = "ner"
    pipe_path = "" # leave empty if the pipe is a spacy native pipe
    level = "node" # node or corpus
    type = "text" # for now we support text - later url, image
    annotated_vertex_name="TextNode"

    [annotator.EmpathAnnotator] ## Spacy customized
    annotator_class ="cag.graph_framework.components.annotators.instance.empath_annotator.EmpathAnnotator"
    vertex_class = "cag.graph_framework.components.annotators.element.graph_elements.EmpathNode"
    edge_class = "cag.graph_framework.components.annotators.element.graph_elements.HasAnnotation"
    pipe = "empath_component"
    pipe_path = "cag.graph_framework.components.annotators.pipe.linguistic.style_features" # leave empty if the pipe is a spacy native pipe
    level = "node" # node or corpus
    type = "text" # for now we support text - later url, image
    annotated_vertex_name="TextNode"

    [annotator.DummyDefaultAnnotator] ## ner is the key for this annotator to get all the variables
    annotator_class ="cag.graph_framework.components.annotators.instance.dummy.DummyDefaultAnnotator"
    vertex_class = "cag.graph_framework.graph.nodes.GenericNode"
    edge_class = "cag.graph_framework.components.annotators.element.graph_elements.HasAnnotation"
    pipe = "customized_pipe_func" # for spacy pipe name, for
    pipe_path = "cag.graph_framework.components.annotators.instance.dummy" # leave empty if the pipe is a spacy native pipe
    level = "node" # node or corpus
    type = "text" # for now we support text - later url, image
    annotated_vertex_name="TextNode"


## TO ADD AN Annotator, add the following entries
###

#[[annotator.{key}]] ## key is the key for this annotator to get all the variables
#annotator_class = ""   # annotator class path - this class has a class variable, NAME = {key}
#vertex_class = ""      # vertex class path
#edge_class = ""        # edge class path
#pipe =""               #""pipe_name" # the spacy pipe name
#level = ""             #"TEXT" or "CORPUS"



