[annotator]

    [annotator.NamedEntityAnnotator] ## ner is the key for this annotator to get all the variables
    annotator_class ="cag.graph_framework.components.annotators.elements.ner_annotator.NamedEntityAnnotator"
    vertex_class = "cag.graph_framework.components.annotators.elements.collections.NamedEntityNode"
    edge_class = "cag.graph_framework.components.annotators.elements.collections.HasAnnotation"
    pipe = "ner"
    level = "TEXT"
    annotated_vertex_name="TextNode"


## TO ADD AN Annotator, add the following entries
###

#[[annotator.{key}]] ## key is the key for this annotator to get all the variables
#annotator_class = ""   # annotator class path - this class has a class variable, NAME = {key}
#vertex_class = ""      # vertex class path
#edge_class = ""        # edge class path
#pipe =""               #""pipe_name" # the spacy pipe name
#level = ""             #"TEXT" or "CORPUS"



