name: Run Pytest

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ArangoDB
        uses: docker://arangodb/arangodb:latest
        with:
          args: >
            --name my-arangodb-container
            -p 8529:8529
            -e ARANGO_NO_AUTH=1
      - name: Wait for ArangoDB to start
        run: |
          while ! curl -sSf http://localhost:8529/_api/version; do
            sleep 1
          done
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytest
        run: pytest tests/